################################
# OWT WebRTC Conference Sample

FROM owt-server:latest

ENV APP_PATH=/owt-client-javascript/dist/samples/conference

WORKDIR /owt-server

RUN ./scripts/build.js -t all --check
RUN ./scripts/pack.js -t all --install-module --app-path $APP_PATH .

RUN ./dist/video_agent/install_openh264.sh
